export const DATASET_SNIPPETS = [
  "The table is called 'trips' and contains NYC Yellow Taxi trip records from January 2025.",
  "VendorID is code indicating the provider: 1=Creative Mobile Technologies, 2=Curb Mobility, 6=Myle Technologies, 7=Helix",
  "tpep_pickup_datetime and tpep_dropoff_datetime are the trip start and end timestamps, stored as TIMESTAMP.",
  "trip_distance is measured in miles.",
  "fare_amount is the base metered fare in USD, before tips and surcharges.",
  "extra is Miscellaneous extras and surcharges.",
  "store_and_fwd_flag  indicates whether the trip record was held in vehicle memory before sending to the vendo: Y= store and forward trip, N=not a store and forward trip",
  "airport_fee is only for pick up at LaGuardia and John F. Kennedy Airports",
  "tip_amount is only populated for credit card payments; cash tips are not recorded and appear as 0.",
  "total_amount is the sum of all charges, does not include cash tips: fare_amount + extra + mta_tax + tip_amount + tolls_amount + improvement_surcharge + congestion_surcharge.",
  "payment_type is an integer code: 0= Flex Fare trip, 1 = Credit card, 2 = Cash, 3 = No charge, 4 = Dispute, 5 = Unknown, 6 = Voided trip.",
  "RatecodeID is an integer code: 1 = Standard rate, 2 = JFK, 3 = Newark, 4 = Nassau or Westchester, 5 = Negotiated fare, 6 = Group ride, 99=Null/ unknown.",
  "PULocationID and DOLocationID are pickup and drop-off zone IDs, referencing NYC TLC taxi zones in which the taximeter was engaged/ disengaged",
  "passenger_count is the number of passengers in the vehicle",
  "To compute trip duration, subtract tpep_pickup_datetime from tpep_dropoff_datetime, e.g. date_diff('minute', tpep_pickup_datetime, tpep_dropoff_datetime).",
  "A 'busy' or 'popular' time/location generally means highest COUNT(*) of trips",
  "Average fare should typically use AVG(fare_amount), not AVG(total_amount), unless the question explicitly asks about total cost to the passenger.",
  "Example: 'How many trips happened on January 15th?' -> SELECT COUNT(*) FROM trips WHERE date_trunc('day', tpep_pickup_datetime) = DATE '2025-01-15'.",
  "Example: 'What is the average trip distance?' -> SELECT AVG(trip_distance) FROM trips.",
  "Example: 'Which payment type is most common?' -> SELECT payment_type, COUNT(*) AS cnt FROM trips GROUP BY payment_type ORDER BY cnt DESC LIMIT 1.",
  "Example: 'What is the total revenue from tips?' -> SELECT SUM(tip_amount) FROM trips.",
  "Example: 'Show me the 5 longest trips by distance' -> SELECT * FROM trips ORDER BY trip_distance DESC LIMIT 5.",
];